Use this to plot loss curves and confusion matrix after training.


In [1]:
import os
import sys
sys.path.append("../src")

import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from pathlib import Path

from data.preprocess import make_classification_dataset

Check if classifier model is working on a few examples

In [5]:
model = tf.keras.models.load_model("../models/classifier_best.keras")

test_dataset, test_size = make_classification_dataset("../data/raw/digits/test", 32)

for images, labels in test_dataset.take(1):
    predictions = model.predict(images)
    predicted_classes = np.argmax(predictions, axis=1)
    true_classes = labels.numpy().astype(int)
    print("predicted: ", predicted_classes)
    print("true: ", true_classes)
    confusion_matrix = tf.math.confusion_matrix(true_classes, predicted_classes)
print(confusion_matrix) 


C:\Users\andre\OneDrive\Documents\AI Projects\Digit Classifier\data\raw\digits\test is the resolved path
Number of images found: 3600
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 715ms/step
predicted:  [4 3 0 1 5 4 2 4 2 0 0 0 2 0 3 4 4 0 2 1 3 3 1 4 3 5 1 5 2 0 2 2]
true:  [4 3 0 1 5 4 2 4 2 0 0 0 2 0 3 4 4 0 2 1 3 3 1 4 3 5 1 5 2 0 2 2]
tf.Tensor(
[[7 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 5 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 3]], shape=(6, 6), dtype=int32)


Add a confusion matrix

ModuleNotFoundError: No module named 'sklearn'